Vagrant.configure("2") do |config|
  # Using Debian 12 for its small footprint
  config.vm.box = "debian/bookworm64"

  # --- SERVER (CONTROL PLANE) ---
  # Only one VM needed for Part 2 (Server mode with apps deployed)
  config.vm.define "aliS" do |s|
    s.vm.hostname = "aliS"
    s.vm.network "private_network", ip: "192.168.56.110"
    s.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 1024
      vb.name = "aliS"
    end
    s.vm.provision "shell", path: "scripts/server_setup.sh"
  end
end
