Vagrant.configure("2") do |config|
  # Debian 12 hafif olduğu için iyi bir tercih
  config.vm.box = "debian/bookworm64"

  # --- L2 PROVIDER AYARLARI (KVM/LIBVIRT) ---
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"
    libvirt.cpu_mode = 'host-passthrough' # Intel iMac CPU özelliklerini L2'ye geçirir
    libvirt.nested = true                 # İç içe sanallaştırmayı aktif eder
    libvirt.nic_model_type = 'virtio'     # Ağ hızı için kritik
    libvirt.disk_bus = 'scsi'             # Disk hızı için kritik
    libvirt.graphics_type = 'none'        # L2'lerde arayüze gerek yok, RAM kazandırır
  end

  # --- SERVER (CONTROL PLANE) ---
  # Only one VM needed for Part 2 (Server mode with apps deployed)
  config.vm.define "aliS" do |s|
    s.vm.hostname = "aliS"
    s.vm.network "private_network", ip: "192.168.56.110", libvirt__forward_mode: "none"

    s.vm.provider :libvirt do |v|
      v.memory = 1024
      v.cpus = 1
    end
    s.vm.provision "shell", path: "scripts/server_setup.sh"
  end
end
