Vagrant.configure("2") do |config|
  # Using Debian 12 for its small footprint
  config.vm.box = "debian/bookworm64"

  # --- SERVER (CONTROL PLANE) ---
  config.vm.define "aliS" do |s|
    s.vm.hostname = "aliS"
    s.vm.network "private_network", ip: "192.168.56.110"
    s.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 1024
      vb.name = "aliS"
    end
    s.vm.provision "shell", path: "scripts/server_setup.sh"
  end

  # --- WORKER (AGENT) ---
  config.vm.define "aliSW" do |sw|
    sw.vm.hostname = "aliSW"
    sw.vm.network "private_network", ip: "192.168.56.111"
    sw.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 1024
      vb.name = "aliSW"
    end
    sw.vm.provision "shell", path: "scripts/worker_setup.sh"
  end
end